In [2]:
import pickle 
import pprint

# The filename of the pickle file you want to open
f = 'df_race_results_2023.pkl'

# Open the file in binary read mode ('rb') and use pickle.load() to load the data
with open(f, 'rb') as file:
    df_race_results = pickle.load(file)

In [28]:
import pickle 
import pprint

# The filename of the pickle file you want to open
f = 'df_qualifying_results_2023.pkl'

# Open the file in binary read mode ('rb') and use pickle.load() to load the data
with open(f, 'rb') as file:
    df_qualifying_results = pickle.load(file)

In [4]:
import pickle 
import pprint

# The filename of the pickle file you want to open
f = 'df_drivers_2023.pkl'

# Open the file in binary read mode ('rb') and use pickle.load() to load the data
with open(f, 'rb') as file:
    df_drivers = pickle.load(file)

In [5]:
import pickle 
import pprint

# The filename of the pickle file you want to open
f = 'df_teams_2023.pkl'

# Open the file in binary read mode ('rb') and use pickle.load() to load the data
with open(f, 'rb') as file:
    df_teams = pickle.load(file)

In [6]:
import pickle 
import pprint

# The filename of the pickle file you want to open
f = 'df_sprint_results_2023.pkl'

# Open the file in binary read mode ('rb') and use pickle.load() to load the data
with open(f, 'rb') as file:
    df_sprint_results = pickle.load(file)

In [7]:
# TO DO

# Model teams data per season, store it locally and create a DataFrame - TO DO
# Model drivers data per season, store it locally and create a DataFrame - TO DO

In [8]:
import pandas as pd
import numpy as np

In [9]:
df_drivers

,season,driver_name,driver_surname,driver_code,driver_date_of_birth,driver_nationality,driver_perm_number
0,2023,Alexander,Albon,ALB,1996-03-23,Thai,23
1,2023,Fernando,Alonso,ALO,1981-07-29,Spanish,14
2,2023,Valtteri,Bottas,BOT,1989-08-28,Finnish,77
3,2023,Nyck,de Vries,DEV,1995-02-06,Dutch,21
4,2023,Pierre,Gasly,GAS,1996-02-07,French,10
5,2023,Lewis,Hamilton,HAM,1985-01-07,British,44
6,2023,Nico,Hülkenberg,HUL,1987-08-19,German,27
7,2023,Liam,Lawson,LAW,2002-02-11,New Zealander,40
8,2023,Charles,Leclerc,LEC,1997-10-16,Monegasque,16
9,2023,Kevin,Magnussen,MAG,1992-10-05,Danish,20
10,2023,Lando,Norris,NOR,1999-11-13,British,4
11,2023,Esteban,Ocon,OCO,1996-09-17,French,31
12,2023,Sergio,Pérez,PER,1990-01-26,Mexican,11
13,2023,Oscar,Piastri,PIA,2001-04-06,Australian,81
14,2023,Daniel,Ricciardo,RIC,1989-07-01,Australian,3
15,2023,George,Russell,RUS,1998-02-15,British,63
16,2023,Carlos,Sainz,SAI,1994-09-01,Spanish,55
17,2023,Logan,Sargeant,SAR,2000-12-31,American,2
18,2023,Lance,Stroll,STR,1998-10-29,Canadian,18
19,2023,Yuki,Tsunoda,TSU,2000-05-11,Japanese,22
20,2023,Max,Verstappen,VER,1997-09-30,Dutch,33
21,2023,Guanyu,Zhou,ZHO,1999-05-30,Chinese,24

In [10]:
df_race_results.head(5)

,season,round,circuit,date,laps,first_name,last_name,driver_code,starting_position,ending_position,points,status,fastest_lap_time,fastest_lap_avg_speed,fastest_lap_rank,fastest_lap_lap,team,team_id
0,2023,1,Bahrain Grand Prix,2023-03-05,57,Max,Verstappen,VER,1,1,25,Finished,1:36.236,202.452,6,44,Red Bull,red_bull
1,2023,1,Bahrain Grand Prix,2023-03-05,57,Sergio,Pérez,PER,2,2,18,Finished,1:36.344,202.225,7,37,Red Bull,red_bull
2,2023,1,Bahrain Grand Prix,2023-03-05,57,Fernando,Alonso,ALO,5,3,15,Finished,1:36.156,202.620,5,36,Aston Martin,aston_martin
3,2023,1,Bahrain Grand Prix,2023-03-05,57,Carlos,Sainz,SAI,4,4,12,Finished,1:37.130,200.588,14,37,Ferrari,ferrari
4,2023,1,Bahrain Grand Prix,2023-03-05,57,Lewis,Hamilton,HAM,7,5,10,Finished,1:36.546,201.802,10,36,Mercedes,mercedes

In [11]:
df_sprint_results

,season,round,circuit,date,time,position,points,driver_name,driver_surname,driver_code,constructor
0,2023,4,Azerbaijan Grand Prix,2023-04-30,11:00:00Z,1,8,Sergio,Pérez,PER,Red Bull
1,2023,4,Azerbaijan Grand Prix,2023-04-30,11:00:00Z,2,7,Charles,Leclerc,LEC,Ferrari
2,2023,4,Azerbaijan Grand Prix,2023-04-30,11:00:00Z,3,6,Max,Verstappen,VER,Red Bull
3,2023,4,Azerbaijan Grand Prix,2023-04-30,11:00:00Z,4,5,George,Russell,RUS,Mercedes
4,2023,4,Azerbaijan Grand Prix,2023-04-30,11:00:00Z,5,4,Carlos,Sainz,SAI,Ferrari
...,...,...,...,...,...,...,...,...,...,...,...
115,2023,20,São Paulo Grand Prix,2023-11-05,17:00:00Z,16,0,Kevin,Magnussen,MAG,Haas F1 Team
116,2023,20,São Paulo Grand Prix,2023-11-05,17:00:00Z,17,0,Guanyu,Zhou,ZHO,Alfa Romeo
117,2023,20,São Paulo Grand Prix,2023-11-05,17:00:00Z,18,0,Nico,Hülkenberg,HUL,Haas F1 Team
118,2023,20,São Paulo Grand Prix,2023-11-05,17:00:00Z,19,0,Valtteri,Bottas,BOT,Alfa Romeo
119,2023,20,São Paulo Grand Prix,2023-11-05,17:00:00Z,20,0,Logan,Sargeant,SAR,Williams

In [12]:
# Drivers data modelling:
# Each driver will have his own table
# Aggregations made from races:
# - Total points in Season - done
# - Total races completed - done
# - Total fastest laps
# - Total pole positions
# - Times qualified better than teammate
# - Average qualifying delta vs teammate
# - Total DNFs - done
# - Total Crashes - done
# - DNFs rate - done
# - Crash rate - done
# - Total overtakes in season - not in current data
# - Average points per race - done
# - Average starting position - done
# - Average qualifying position
# - Average ending position - done
# - Total points in Sprint
# - Average Finishing position Sprint - done

In [13]:
df_race_results.head(5)

,season,round,circuit,date,laps,first_name,last_name,driver_code,starting_position,ending_position,points,status,fastest_lap_time,fastest_lap_avg_speed,fastest_lap_rank,fastest_lap_lap,team,team_id
0,2023,1,Bahrain Grand Prix,2023-03-05,57,Max,Verstappen,VER,1,1,25,Finished,1:36.236,202.452,6,44,Red Bull,red_bull
1,2023,1,Bahrain Grand Prix,2023-03-05,57,Sergio,Pérez,PER,2,2,18,Finished,1:36.344,202.225,7,37,Red Bull,red_bull
2,2023,1,Bahrain Grand Prix,2023-03-05,57,Fernando,Alonso,ALO,5,3,15,Finished,1:36.156,202.620,5,36,Aston Martin,aston_martin
3,2023,1,Bahrain Grand Prix,2023-03-05,57,Carlos,Sainz,SAI,4,4,12,Finished,1:37.130,200.588,14,37,Ferrari,ferrari
4,2023,1,Bahrain Grand Prix,2023-03-05,57,Lewis,Hamilton,HAM,7,5,10,Finished,1:36.546,201.802,10,36,Mercedes,mercedes

In [21]:
df_sprint_results.head(5)

,season,round,circuit,date,time,position,points,driver_name,driver_surname,driver_code,constructor
0,2023,4,Azerbaijan Grand Prix,2023-04-30,11:00:00Z,1,8,Sergio,Pérez,PER,Red Bull
1,2023,4,Azerbaijan Grand Prix,2023-04-30,11:00:00Z,2,7,Charles,Leclerc,LEC,Ferrari
2,2023,4,Azerbaijan Grand Prix,2023-04-30,11:00:00Z,3,6,Max,Verstappen,VER,Red Bull
3,2023,4,Azerbaijan Grand Prix,2023-04-30,11:00:00Z,4,5,George,Russell,RUS,Mercedes
4,2023,4,Azerbaijan Grand Prix,2023-04-30,11:00:00Z,5,4,Carlos,Sainz,SAI,Ferrari

In [24]:
df_qualifying_results.head(5)

,season,round,date,time,position,q1,q2,q3,driver_name,driver_surname,constructor
0,2023,1,2023-03-05,15:00:00Z,1,1:31.295,1:31.295,1:31.295,Max,Verstappen,Red Bull
1,2023,1,2023-03-05,15:00:00Z,2,1:31.479,1:31.479,1:31.479,Sergio,Pérez,Red Bull
2,2023,1,2023-03-05,15:00:00Z,3,1:31.094,1:31.094,1:31.094,Charles,Leclerc,Ferrari
3,2023,1,2023-03-05,15:00:00Z,4,1:30.993,1:30.993,1:30.993,Carlos,Sainz,Ferrari
4,2023,1,2023-03-05,15:00:00Z,5,1:31.158,1:31.158,1:31.158,Fernando,Alonso,Aston Martin

In [18]:
# Drivers data modelling:
# Each driver will have his own table
# Aggregations made from races:
# - Total points in Season - done
# - Total races completed - done
# - Total fastest laps
# - Total pole positions
# - Times qualified better than teammate
# - Average qualifying delta vs teammate
# - Total DNFs - done
# - Total Crashes - done
# - DNFs rate - done
# - Crash rate - done
# - To  tal overtakes in season - not in current data
# - Average points per race - done
# - Average starting position - done
# - Average qualifying position
# - Average ending position - done
# - Total points in Sprint - done
# - Average Starting position Sprint - done
# - Average Finishing position Sprint - done

In [20]:
df_sprint_results[df_sprint_results['driver_code'] == 'ALO']['points'].sum()

'340100'

In [33]:
df_q_alo = df_qualifying_results2[df_qualifying_results2['driver_code'] == 'ALO']
df_q_alo.head(5)

,season,round,date,time,position,q1,q2,q3,driver_name,driver_surname,driver_code,constructor
4,2023,1,2023-03-05,15:00:00Z,5,1:31.158,1:31.158,1:31.158,Fernando,Alonso,ALO,Aston Martin
22,2023,2,2023-03-19,17:00:00Z,3,1:29.298,1:29.298,1:29.298,Fernando,Alonso,ALO,Aston Martin
43,2023,3,2023-04-02,05:00:00Z,4,1:17.832,1:17.832,1:17.832,Fernando,Alonso,ALO,Aston Martin
65,2023,4,2023-04-30,11:00:00Z,6,1:41.720,1:41.720,1:41.720,Fernando,Alonso,ALO,Aston Martin
81,2023,5,2023-05-07,19:30:00Z,2,1:28.179,1:28.179,1:28.179,Fernando,Alonso,ALO,Aston Martin

In [34]:
import numpy as np
import math

df_race_results2 = df_race_results.copy()
df_sprint_results2 = df_sprint_results.copy()
df_drivers2 = df_drivers.copy()
df_qualifying_results2 = df_qualifying_results.copy()
df_d_alo = df_drivers2[df_drivers['driver_code'] == 'ALO']
df_r_alo = df_race_results2[df_race_results2['driver_code'] == 'ALO']
df_s_alo = df_sprint_results2[df_sprint_results2['driver_code'] == 'ALO']
df_q_alo = df_qualifying_results2[df_qualifying_results2['driver_code'] == 'ALO']

df_d_alo['total_points_races'] = df_r_alo['points'].sum()
df_d_alo['total_races_completed'] = df_r_alo[df_r_alo['status'] == 'Finished']['circuit'].count()
df_d_alo['total_dnfs'] = df_r_alo[~df_r_alo['status'].isin(['Finished', '+1 Lap', '+2 Laps'])]['circuit'].count()
df_d_alo['total_crashes'] = df_r_alo[df_r_alo['status'] == 'Collision']['circuit'].count()
df_d_alo['dnf_ratio'] = round((df_d_alo['total_dnfs']/df_r_alo['circuit'].count())* 100, 2).astype(str) + '%'
df_d_alo['crash_ratio'] = round((df_d_alo['total_crashes']/df_r_alo['circuit'].count())* 100, 2).astype(str) + '%'
df_d_alo['avg_points_per_race'] = math.trunc(np.ceil(df_r_alo['points'].mean()))
df_d_alo['avg_starting_position'] = math.trunc(np.ceil(df_r_alo['starting_position'].mean()))
df_d_alo['avg_ending_position_race'] = math.trunc(np.ceil(df_r_alo['ending_position'].mean()))
df_d_alo['avg_ending_position_sprint'] = math.trunc(df_s_alo['position'].mean())
df_d_alo['avg_points_per_sprint'] = math.trunc(np.ceil(df_s_alo['points'].mean()))
df_d_alo['total_points_sprint'] = df_s_alo['points'].sum()
df_d_alo['avg_qualifying_position'] = df_q_alo['q3'].mean()

df_d_alo

/tmp/ipykernel_188922/3474377161.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['total_points_races'] = df_r_alo['points'].sum()
/tmp/ipykernel_188922/3474377161.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['total_races_completed'] = df_r_alo[df_r_alo['status'] == 'Finished']['circuit'].count()
/tmp/ipykernel_188922/3474377161.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['total_dnfs'] = df_r_alo[~df_r_alo['status'].isin(['Finished', '+1 Lap', '+2 Laps'])]['circuit'].count()
/tmp/ipykernel_188922/3474377161.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['total_crashes'] = df_r_alo[df_r_alo['status'] == 'Collision']['circuit'].count()
/tmp/ipykernel_188922/3474377161.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['dnf_ratio'] = round((df_d_alo['total_dnfs']/df_r_alo['circuit'].count())* 100, 2).astype(str) + '%'
/tmp/ipykernel_188922/3474377161.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['crash_ratio'] = round((df_d_alo['total_crashes']/df_r_alo['circuit'].count())* 100, 2).astype(str) + '%'
/tmp/ipykernel_188922/3474377161.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['avg_points_per_race'] = math.trunc(np.ceil(df_r_alo['points'].mean()))
/tmp/ipykernel_188922/3474377161.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['avg_starting_position'] = math.trunc(np.ceil(df_r_alo['starting_position'].mean()))
/tmp/ipykernel_188922/3474377161.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['avg_ending_position_race'] = math.trunc(np.ceil(df_r_alo['ending_position'].mean()))
/tmp/ipykernel_188922/3474377161.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['avg_ending_position_sprint'] = math.trunc(df_s_alo['position'].mean())
/tmp/ipykernel_188922/3474377161.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['avg_points_per_sprint'] = math.trunc(np.ceil(df_s_alo['points'].mean()))
/tmp/ipykernel_188922/3474377161.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_d_alo['total_points_sprint'] = df_s_alo['points'].sum()

TypeError: Could not convert 1:31.1581:29.2981:17.8321:41.7201:28.1791:12.8861:13.7471:21.4811:05.6551:29.9491:18.5801:58.8341:21.8401:22.0431:32.5841:30.9711:25.2231:36.2681:18.8481:10.5571:34.4221:24.501 to numeric

In [ ]:
def format_time(ms):
    # Convert milliseconds to total seconds
    seconds = int(ms // 1000)
    milliseconds = int(ms % 1000)
    minutes = seconds // 60
    seconds = seconds % 60
    
    # Format as mm:ss:ms
    return f"{minutes:02}:{seconds:02}:{milliseconds:03}"

# Apply the formatting function to the DataFrame column
df['FormattedTime'] = df['TimeInMilliseconds'].apply(format_time)

In [ ]:
# - Total points in Season

df_race_results.groupby(['driver_code'])['points'].sum()

In [ ]:
# - Total races completed

df_race_results['status'].unique()
df_race_results[df_race_results['status'] == 'Finished'].groupby(['driver_code'])['circuit'].count()
df_race_results['races_finished'] = df_race_results[df_race_results['status'] == 'Finished'].groupby(['driver_code'])['circuit'].count()
df_race_results['races_finished']
# - Total fastest laps
# - Total pole positions
# - Times qualified better than teammate
# - Average qualifying delta vs teammate
# - Total DNFs
# - Total Crashes
# - DNFs rate
# - Crash rate
# - Total overtakes in season - not in current data
# - Average points per race
# - Average starting position
# - Average qualifying position
# - Average ending position

In [ ]:
# Teams data modelling:
# Each team will have its own table
# Aggregations made from races:
# - Total points in Season
# - Total fastest laps
# - Total DNFs
# - Total Crashes
# - Crash rate
# - DNFs rate
# - Average points per race
# - Fastest Pitstop
# - Pitstop Average Time per race
# - Fastest Pitstop Time Rank compared to other teams
# - Total races completed
# - Total overtakes in season - not in current data
# - Average starting position
# - Average qualifying position
# - Average ending position